name: Metrics

on:
  schedule: [{ cron: "0 */6 * * *" }]
  workflow_dispatch:
  push:
    branches:
      - "main"
      
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: 📘 Classic template
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: ichirei
          template: classic
          filename: ichirei.svg
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: large
          config_timezone: Asia/Jakarta
