name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push:
    branches:
      - "main"
      
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: 📘 Classic template
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: ichirei
          template: classic
          filename: ichirei.svg
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: large
          config_timezone: Asia/Jakarta
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          
          # RecentActivity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes
          plugin_activity_filter: push, issue, pr, release, fork, review, ref/create, public
          
          # IsoCalendar
          plugin_isocalendar: yes 
          plugin_isocalendar_duration: full-year
